/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHeader {}
  interface AppLayoutStandard {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface AppWrapper {}
  interface ListingCard {
    'item': any;
  }
  interface ListingList {}
  interface ListingSlider {}
  interface MediaLogos {}
  interface NeighborhoodCard {
    'item': any;
  }
  interface NeighborhoodSlider {
    'items': any[];
  }
  interface PageHome {}
  interface SearchFilters {}
}

declare global {

  // Adding a global JSX for backcompatibility with legacy dependencies
  export namespace JSX {
    export interface Element {}
  }


  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppLayoutStandardElement extends Components.AppLayoutStandard, HTMLStencilElement {}
  var HTMLAppLayoutStandardElement: {
    prototype: HTMLAppLayoutStandardElement;
    new (): HTMLAppLayoutStandardElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppWrapperElement extends Components.AppWrapper, HTMLStencilElement {}
  var HTMLAppWrapperElement: {
    prototype: HTMLAppWrapperElement;
    new (): HTMLAppWrapperElement;
  };

  interface HTMLListingCardElement extends Components.ListingCard, HTMLStencilElement {}
  var HTMLListingCardElement: {
    prototype: HTMLListingCardElement;
    new (): HTMLListingCardElement;
  };

  interface HTMLListingListElement extends Components.ListingList, HTMLStencilElement {}
  var HTMLListingListElement: {
    prototype: HTMLListingListElement;
    new (): HTMLListingListElement;
  };

  interface HTMLListingSliderElement extends Components.ListingSlider, HTMLStencilElement {}
  var HTMLListingSliderElement: {
    prototype: HTMLListingSliderElement;
    new (): HTMLListingSliderElement;
  };

  interface HTMLMediaLogosElement extends Components.MediaLogos, HTMLStencilElement {}
  var HTMLMediaLogosElement: {
    prototype: HTMLMediaLogosElement;
    new (): HTMLMediaLogosElement;
  };

  interface HTMLNeighborhoodCardElement extends Components.NeighborhoodCard, HTMLStencilElement {}
  var HTMLNeighborhoodCardElement: {
    prototype: HTMLNeighborhoodCardElement;
    new (): HTMLNeighborhoodCardElement;
  };

  interface HTMLNeighborhoodSliderElement extends Components.NeighborhoodSlider, HTMLStencilElement {}
  var HTMLNeighborhoodSliderElement: {
    prototype: HTMLNeighborhoodSliderElement;
    new (): HTMLNeighborhoodSliderElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };

  interface HTMLSearchFiltersElement extends Components.SearchFilters, HTMLStencilElement {}
  var HTMLSearchFiltersElement: {
    prototype: HTMLSearchFiltersElement;
    new (): HTMLSearchFiltersElement;
  };
  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
    'app-layout-standard': HTMLAppLayoutStandardElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-wrapper': HTMLAppWrapperElement;
    'listing-card': HTMLListingCardElement;
    'listing-list': HTMLListingListElement;
    'listing-slider': HTMLListingSliderElement;
    'media-logos': HTMLMediaLogosElement;
    'neighborhood-card': HTMLNeighborhoodCardElement;
    'neighborhood-slider': HTMLNeighborhoodSliderElement;
    'page-home': HTMLPageHomeElement;
    'search-filters': HTMLSearchFiltersElement;
  }
}

declare namespace LocalJSX {
  interface AppHeader extends JSXBase.HTMLAttributes<HTMLAppHeaderElement> {}
  interface AppLayoutStandard extends JSXBase.HTMLAttributes<HTMLAppLayoutStandardElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'name'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppWrapper extends JSXBase.HTMLAttributes<HTMLAppWrapperElement> {}
  interface ListingCard extends JSXBase.HTMLAttributes<HTMLListingCardElement> {
    'item'?: any;
  }
  interface ListingList extends JSXBase.HTMLAttributes<HTMLListingListElement> {}
  interface ListingSlider extends JSXBase.HTMLAttributes<HTMLListingSliderElement> {}
  interface MediaLogos extends JSXBase.HTMLAttributes<HTMLMediaLogosElement> {}
  interface NeighborhoodCard extends JSXBase.HTMLAttributes<HTMLNeighborhoodCardElement> {
    'item'?: any;
  }
  interface NeighborhoodSlider extends JSXBase.HTMLAttributes<HTMLNeighborhoodSliderElement> {
    'items'?: any[];
  }
  interface PageHome extends JSXBase.HTMLAttributes<HTMLPageHomeElement> {}
  interface SearchFilters extends JSXBase.HTMLAttributes<HTMLSearchFiltersElement> {}

  interface IntrinsicElements {
    'app-header': AppHeader;
    'app-layout-standard': AppLayoutStandard;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-wrapper': AppWrapper;
    'listing-card': ListingCard;
    'listing-list': ListingList;
    'listing-slider': ListingSlider;
    'media-logos': MediaLogos;
    'neighborhood-card': NeighborhoodCard;
    'neighborhood-slider': NeighborhoodSlider;
    'page-home': PageHome;
    'search-filters': SearchFilters;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


